# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Deep Learning実習
#email: kyamagu@vision.is.tohoku.ac.jp
description: > # this means to ignore newlines until "baseurl:"
  Caffeフレームワークを利用した画像認識実習
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kyamagu.github.io/dl-workshop-2016/" # the base hostname & protocol for your site
#twitter_username: kotymg
github_username:  kyamagu

# Build settings
markdown: kramdown
future: true
